package com.alrosa.staa.gatekeeper;

public enum Direction {
    MAIN,
    BUREAU, USERS, ADMINS, OPERATORS, GLOBAL_ACCESS_LEVELS, CARDS, CARD_LAYOUTS, POSITIONS, ORGANIZATIONS,
    MAN, WOMAN, GLOBAL_ACCESS_LEVEL, CARD, CARD_LAYOUT, POSITION, ORGANIZATION, OFFICE,
    COMPUTER, CONSOLE,
    SERVER, PERCO,  PERCOC01, CARDREADER;


}
