package com.alrosa.staa.gatekeeper;

public enum Direction {
    MAIN, SERVER, COMPUTER, BUREAU,
    PERCO, PERCO_C01, CARDREADER,
    USERS, ADMINS, OPERATORS, GLOBAL_ACCESS_LEVELS,
    CARDS, CARD_LAYOUTS, POSITIONS, ORGANIZATIONS,
    MAN, WOMAN, GLOBAL_ACCESS_LEVEL, CARD,
    CARD_LAYOUT, POSITION, ORGANIZATION, OFFICE,
    CONSOLE;
}
